---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1
  - name: centos-6.6
  - name: ubuntu-14.04
  - name: ubuntu-15.04

suites:
  - name: default
    run_list:
      - recipe[zip_app::default]
    attributes:
